//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class employ_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employ_user()
        {
            this.userRoles = new HashSet<userRole>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string department { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string Designation { get; set; }
        public Nullable<int> departmentId { get; set; }
        public Nullable<int> DesignationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userRole> userRoles { get; set; }
        public virtual department department1 { get; set; }
        public virtual Designation Designation1 { get; set; }
    }
}
